### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by ytaylor** [Adalab/modulo-2-evaluacion-intermedia-Natalia-GP#1]
Really cool job @Natalia-GP !!!

Here you have some tips to improve the exercise:

### JavaScript: basic
- [x] Watch out for selector names used in `querySelector()` methods... they must start with `.` : https://github.com/Adalab/modulo-2-evaluacion-intermedia-Natalia-GP/blob/c47ae0a52038fa6a16dcd6f3554f4dd79681bfbd/main.js#L4-L6 
- [x] Remove the variables which are never used: https://github.com/Adalab/modulo-2-evaluacion-intermedia-Natalia-GP/blob/c47ae0a52038fa6a16dcd6f3554f4dd79681bfbd/main.js#L8 

### JavaScript: advanced

- [x] Check if the `<select>` has the default option (with no value). There should be an initial option that says `Seleccione la raza`

### Good practices

- [x] Make multiple commits as you work. 
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text.
- [x] Try to improve your commits messages. "js" is a bit poor. "Add random number logic" is more explanatory.

### Structure
- [x] Define a good structure of folders and files for the project.

### CSS

- [ ] Avoid adding styles until the js code is solid as a rock.

### Steps to bonus the game

You are close to the exercise solution, but here you have a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables.
2. Use three counter variables: one for user wins, other for computer wins and another for total rounds played.
4. Increment the counter for computer wins when the computer wins a round (find the correct conditions).
5. Increment the round counter always the user clicks on "Batalla" button.
6. Show the counters in the proper elements of the page.
8. Create other function to check if the players have reached the maximum limit of rounds and call it from the listener function.
9. Add a reset button that cleans the select, the counter and writes the initial feedback

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Show an image with the user and computer selection
- Make the input work when selecting the option.
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by ytaylordev** [comment]
Good Job :)
